POST https://tellyport.swn14.deno.net/api/registration/api-key HTTP/1.1
content-type: application/json

{
    "emailAddress": "swnofer@gmail.com"
}

### 

GET http://localhost:3000/api/tv/random-episode?seriesId=1447
Content-Type: application/json
X-API-Key: 6f3bcd16-cd06-4d59-817b-18cad8c5aa81

###

GET https://tellyport.swn14.deno.net/api/tv/search?query=person of interest
Content-Type: application/json
X-API-Key: 6f3bcd16-cd06-4d59-817b-18cad8c5aa81

###

GET https://tellyport.swn14.deno.net/api/tv/random-episode?seriesId=1411
Content-Type: application/json
X-API-Key: 6f3bcd16-cd06-4d59-817b-18cad8c5aa81